### ISSUE TITLE
AutoScrolling stops after GameObject holding CarouselView (or it's parent) is switched off and on again

### ISSUE THREAD

**Issue by VarunStepApp** [Haruma-K/FancyCarouselView#10]
So I ran into this problem where turning off the GameObject that contains the CarouselView script and turning it on again will stop its auto-scrolling

I have tried to set AutoScrollingEnabled to true on OnEnable() calls, but to no avail

The user has to initiate a drag to restart the autoscrolling again

refer to the gif below for a visual reference

![Bug](https://github.com/Haruma-K/FancyCarouselView/assets/128783628/977396b4-2926-4dab-9796-cf56d2f81fa5)

**Comment by Haruma-K** [comment]
Thanks for the report!
I will fix it later.

**Comment by Haruma-K** [comment]
@VarunStepApp 
Fixed in 1.1.5. thank you!
https://github.com/Haruma-K/FancyCarouselView/releases/tag/1.1.5
