### ISSUE TITLE
Cell image isn't displaying until carousel scrolls first

### ISSUE THREAD

**Issue by brandonchew** [Haruma-K/FancyCarouselView#11]
I've created a cell object with a render texture for the carousel.  It loads up the texture properly and can confirm its there in the inspector window at runtime.  I have 3 cells being generated, but the first two don't actually display the texture at runtime until I scroll two spots, either from 1 -> 3 or 1 -> 2 -> 1.  The cells seem to refresh by then and display everything correctly.  Is there someway for me to refresh these cells without having to scroll the carousel to do so?

**Comment by Haruma-K** [comment]
@brandonchew 
You can achieve it by overriding CarouselCell.Refresh  method and implementing the required process, as demonstrated in the example.

https://github.com/Haruma-K/FancyCarouselView/blob/f3ac23c78f1851428f80d1435aad3cf1a9ff6acc/Assets/Demo/Scripts/DemoCarouselCell.cs#L15

**Comment by brandonchew** [comment]
Yea, Thats implemented.  It must be something with my refreshing of the
cell or setting of the raw image then...Thanks for responding.  Will update
when I figure it out on my end.

**Comment by brandonchew** [comment]
Figured it out.  My code was initializing the opacity of the image to 0 which made it 'not visible' until it was refreshed to have a visible opacity.
