### ISSUE TITLE
Resetting carousel does not reset the active cell position

### ISSUE THREAD

**Issue by brandonchew** [Haruma-K/FancyCarouselView#12]
Is there a way to reset the carousel contents and positioning?

I've called Cleanup on the carousel view and update the contents of the view, but when its shown, the active index is the same as it was before I called cleanup.

**Comment by Haruma-K** [comment]
Surely, it seems natural for it to reset. I'll fix it.

**Comment by Haruma-K** [comment]
@brandonchew 
Released as 1.1.6, enjoy!
https://github.com/Haruma-K/FancyCarouselView/releases/tag/1.1.6

**Comment by Haruma-K** [comment]
thanks for your report.
