### ISSUE TITLE
On odd numbered carousel counts, carousel cell calls "Refresh" multiple times 

### ISSUE THREAD

**Issue by brandonchew** [Haruma-K/FancyCarouselView#14]
Situation:
I have a carousel where only 1 item is displayed at a time.  When there is an odd number of cells in the carousel and I switch from the first cell to the last (and vice versa), the active cell flickers while updating the texture.  This is because the active cell switches from being enabled and then switches back to the other game object being enabled.  

I noticed that because only one cell is being displayed at a time, it switches between two game objects to store the active texture of the cell being displayed.  When there is an odd numbered count, switching from first to last (and vice versa) initially makes the second game object cell active, then immediately switches back to the original game object.  

Is there something logic-wise with calculating which game object should be active that can be done?  I was noticing the issue happening in the FancyScrollView.UpdateCells method.

**Comment by brandonchew** [comment]
Hi, not sure if you seen this yet or not, but just bumping to see if I can get a response.

**Comment by Haruma-K** [comment]
I realized this late, sorry.

> Is there something logic-wise with calculating which game object should be active that can be done?

There is nothing like that, nor do I plan to add it.

I'm not sure what you want to do, but what do you mean by updating the texture? If you can give me a minimal project that reproduces this, I might be able to help.

**Comment by brandonchew** [comment]
Thanks for getting back to me.  

I noticed you have some logic in there where it will switch between two game objects in the carousel when only 1 cell is being displayed at a time.  When one is displaying, the other is "inactive".  When there is an odd number of cells in the carousel and switching from the last cell to the first again or vice versa, the active cell gameobject starts as being the "second" gameobject in the hierarchy, then switches to be the "first" game object in the hierarchy.  

The texture I'm referring to is instead of just a static image representing the cell, I am using a Texture to display the image instead of a sprite.  

I tried to see if switching your example project to the same parameters for the carousel as I'm seeing the bug, and I see the active/inactive gameobject when switching an odd numbered carousel, but it doesn't flicker.  So maybe its got something to do with my refresh code.  I made the Carousel View in your code to be the same size as the cell (600 x 300) so only 1 cell would be displayed at a time.  Then if you look at the hierarchy, and switch from index 0 -> 2 or 2 -> 0 you can see the gameobjects switching.   

Not sure if i can provide a minimal project to see the issue (due to my company's policies), but i'll try and get a recording of the "flicker" happening and show the game objects going active and inactive.

**Comment by Haruma-K** [comment]
> So maybe its got something to do with my refresh code. 

Is the code set up to complete the texture refresh in one frame? It seems like flickering might occur if you're asynchronously fetching from the web or updating RenderTexture.

**Comment by brandonchew** [comment]
I'm just setting the texture of a RawImage in the scene as part of the refresh.  I don't think it would be because of some asynchronous jobs, but it could be.  This issue is minor and has fallen down our priority list but thank you so much for updating and trying to help.
