### ISSUE TITLE
CarouselScroller inspector is empty

### ISSUE THREAD

**Issue by Tr0sT** [Haruma-K/FancyCarouselView#3]
Unity 2022.1.13f1

And also 244 line of CarouselView.cs shouldn't be like that?
var carouselSize = _scroller.ScrollDirection == ScrollDirection.Horizontal ? rectTrans.rect.width : rectTrans.rect.height; 

And could you please make _cellSize property protected or make public setter? My elements should be full screen, so i need to manually set it

**Comment by Haruma-K** [comment]
Thanks for your input!

First, `CarouselScroller` has no exposed properties.
Editable properies are exposed in the Inspector of the `CarouselView`.

I will check other points from now on.

**Comment by Haruma-K** [comment]
@Tr0sT 
You are correct about the latter two points.
I fixed it and released as v1.1.1.

https://github.com/Haruma-K/FancyCarouselView/releases/tag/1.1.1

Thanks for your information!

> My elements should be full screen,

Maybe I have not fully envisioned your usecase, so if you have any more questions, please let me know.
