### ISSUE TITLE
Scrolling locks up on pinch gesture

### ISSUE THREAD

**Issue by adamsingle** [Haruma-K/FancyCarouselView#6]
There seems to be an issue in the OnBeginDrag method when running this on mobile. If you perform a pinch gesture I believe it is landing in the condition 
`if ((_scroller.ScrollDirection == ScrollDirection.Vertical &&
                 Math.Abs(eventData.delta.x) > Math.Abs(eventData.delta.y))
                || (_scroller.ScrollDirection == ScrollDirection.Horizontal &&
                    Math.Abs(eventData.delta.x) < Math.Abs(eventData.delta.y)))
            {
                _scroller.Draggable = false;
                return;
            }`
which sets Draggable to false and is never set to true again making the carousel non-responsive. For now I've commented out this condition which may introduce other issues, but I'm on a deadline haha. So far it seems to be fine.

**Comment by Haruma-K** [comment]
Thanks for your report! I was able to reproduce it.
I'll try to fix it, please wait.

**Comment by Haruma-K** [comment]
Released as 1.1.2🚀 

https://github.com/Haruma-K/FancyCarouselView/releases/tag/1.1.2

Thanks for your report!

**Comment by adamsingle** [comment]
Thank you
