### ISSUE TITLE
Refresh not being called on the first element after the first time

### ISSUE THREAD

**Issue by adamsingle** [Haruma-K/FancyCarouselView#9]
My testing seems to be showing that the Refresh override method is not getting called on the first element beyond when the carousel is initialised. Each cell after that has Refresh called as you scroll from one to the other, but going back to the first element does not fire it. I suspect the issue is deeper and in FancyScrollView though. Possibly the UpdateCells method

**Comment by adamsingle** [comment]
On top of this, possibly related?, the OnVisibilityChanged callback only seems to be happening for the second item and ONLY with going back to the first element. I cannot find a reliable way, within my CarouselCell class, to know when an element is the "current" one and when it's not. I need some, for example, to play audio while they're the current one and stop it once they're not.

**Comment by adamsingle** [comment]
But the last element, when dragged as if there might be another element beyond it, triggers the visibility changed with a false value every time. But NOT when dragged back to the second last element. Am I missing something about this callback and when it should be fired?

**Comment by adamsingle** [comment]
Also, the CarouselView.CarouseCellVisibilityChanged callback seems to never be called as far as I can tell. The only thing that seems to be reliable is the CarouselView.ActiveCellChanged callback which only gives an index of the new active cell and is useless for doing anything on the actual CellView

**Comment by Haruma-K** [comment]
First, can this be reproduced in my demo?

After reading the entire text above, I understand that your issue consists of the following four points:

1. `Refresh` is not called correctly.
2. `OnVisibilityChanged` is not called correctly.
3. There is no way to distinguish whether it is the "current" cell.
4. `CarouselView.CarouseCellVisibilityChanged` is not called.

For points 1, 2, and 4, I could not reproduce them in my demo.
If you can reproduce them in my demo, please provide the steps to do so.
If you cannot reproduce them in my demo, please provide an another minimal project that can.
Please also let me know the version of FancyScrollView.

For point 3, please implement it as follows:

```cs
FancyCarouselView carouselView;
carouselView.CarouselCellVisibilityChanged += (cell, visibility) =>
{
    // Use carouselView.ActiveCellIndex here
};
```

However, it's not possible for the library to accurately determine what is considered your "current" cell.
(For example, if there are always 5 cells visible on the screen, which one is the "current" cell?)

**Comment by adamsingle** [comment]
I have tried using that callback, it isn't always called. I will take a look at your demo and see, but I am having a heck of a time getting accurate callbacks. I have just one cell on screen at a time and the timing of callbacks is all over the place for me. I'll take a look at the demo

**Comment by adamsingle** [comment]
I added a _carouselView.CarouselCellVisibilityChanged listener in your Demo script and it's never called.

I added some logging into the other methods, and it looks like my issue is that in my carousel, i don't quite have the cells the full width of the screen. Because I don't know what the screen might be, If I do manually set it to the size of the container, I see the results I need with respect to the refresh and visibility calls. However it's still called multiple times during a transition, which makes it hard to use to set up anything. I'm essentially attempting to use this to show pages in a book, some of those pages have buttons on the page to play audio. I can't create those buttons because I can't find a singe callback that only happens once as an element gains visibility.

**Comment by Haruma-K** [comment]
Are you registering the callback after CarouselView.Setup, by any chance?
In that case, it seems that the callback won't be called. If this is the cause, I'll make the necessary corrections.

**Comment by Haruma-K** [comment]
However, considering things like CarouselCellInstantiated, it's still better to register the callback before Setup.

**Comment by adamsingle** [comment]
I see, I didn't know to do that, I'll try registering all the callbacks before Setup. Thanks

**Comment by Haruma-K** [comment]
Did it work well?
Regarding the order of registering callbacks, it is unclear, so I will add it to the documentation later.
